/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Grafo;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-09-21")
public class NullException extends org.apache.thrift.TException implements org.apache.thrift.TBase<NullException, NullException._Fields>, java.io.Serializable, Cloneable, Comparable<NullException> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NullException");

  private static final org.apache.thrift.protocol.TField MENSAGEM_FIELD_DESC = new org.apache.thrift.protocol.TField("mensagem", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new NullExceptionStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new NullExceptionTupleSchemeFactory();

  public java.lang.String mensagem; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MENSAGEM((short)1, "mensagem");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MENSAGEM
          return MENSAGEM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MENSAGEM, new org.apache.thrift.meta_data.FieldMetaData("mensagem", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NullException.class, metaDataMap);
  }

  public NullException() {
  }

  public NullException(
    java.lang.String mensagem)
  {
    this();
    this.mensagem = mensagem;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NullException(NullException other) {
    if (other.isSetMensagem()) {
      this.mensagem = other.mensagem;
    }
  }

  public NullException deepCopy() {
    return new NullException(this);
  }

  @Override
  public void clear() {
    this.mensagem = null;
  }

  public java.lang.String getMensagem() {
    return this.mensagem;
  }

  public NullException setMensagem(java.lang.String mensagem) {
    this.mensagem = mensagem;
    return this;
  }

  public void unsetMensagem() {
    this.mensagem = null;
  }

  /** Returns true if field mensagem is set (has been assigned a value) and false otherwise */
  public boolean isSetMensagem() {
    return this.mensagem != null;
  }

  public void setMensagemIsSet(boolean value) {
    if (!value) {
      this.mensagem = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case MENSAGEM:
      if (value == null) {
        unsetMensagem();
      } else {
        setMensagem((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MENSAGEM:
      return getMensagem();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MENSAGEM:
      return isSetMensagem();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof NullException)
      return this.equals((NullException)that);
    return false;
  }

  public boolean equals(NullException that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_mensagem = true && this.isSetMensagem();
    boolean that_present_mensagem = true && that.isSetMensagem();
    if (this_present_mensagem || that_present_mensagem) {
      if (!(this_present_mensagem && that_present_mensagem))
        return false;
      if (!this.mensagem.equals(that.mensagem))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMensagem()) ? 131071 : 524287);
    if (isSetMensagem())
      hashCode = hashCode * 8191 + mensagem.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(NullException other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetMensagem()).compareTo(other.isSetMensagem());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMensagem()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mensagem, other.mensagem);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("NullException(");
    boolean first = true;

    sb.append("mensagem:");
    if (this.mensagem == null) {
      sb.append("null");
    } else {
      sb.append(this.mensagem);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class NullExceptionStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public NullExceptionStandardScheme getScheme() {
      return new NullExceptionStandardScheme();
    }
  }

  private static class NullExceptionStandardScheme extends org.apache.thrift.scheme.StandardScheme<NullException> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, NullException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MENSAGEM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mensagem = iprot.readString();
              struct.setMensagemIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, NullException struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.mensagem != null) {
        oprot.writeFieldBegin(MENSAGEM_FIELD_DESC);
        oprot.writeString(struct.mensagem);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class NullExceptionTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public NullExceptionTupleScheme getScheme() {
      return new NullExceptionTupleScheme();
    }
  }

  private static class NullExceptionTupleScheme extends org.apache.thrift.scheme.TupleScheme<NullException> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, NullException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetMensagem()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMensagem()) {
        oprot.writeString(struct.mensagem);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, NullException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.mensagem = iprot.readString();
        struct.setMensagemIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

